version: "2"
services:
  cents:
    restart: always
    image: "node:8-alpine"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
      - COOKIE_SECRET=${COOKIE_SECRET}
      - PORT=8070
    volumes:
      - ./server:/app/server
      - ./service:/app/service
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
      - ./accounts.json:/app/accounts.json
      - ./diffs.log:/app/diffs.log
    command: "node server/index.js"

  # this allows rolling updates
  haproxy:
    image: dockercloud/haproxy
    links:
      - cents
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8070:8070
networks:
  default:
    external:
      name: infrastructure_default
